### ISSUE TITLE
Table element

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/sim_platform#4]
Tables extend the default container. Each cell contains sub-elements.
- [x] List of column IDs and values.
- [x] Filter on a list of column IDs.
- [x] Search on a list of column IDs.
- [x] Style for the ~~header, rows, columns, grid~~ background ( colour ), border ( width, colour ).

- Additional actions:

    ~~Collapse~~
    ~~Expand~~
-  [x] Scroll
- [x] Populate / Update

<img width="685" alt="capture d ecran 2019-02-11 a 13 17 36" src="https://user-images.githubusercontent.com/1546847/52562649-7424f400-2dff-11e9-8c99-9442ae5118bb.png">

**Comment by nguyenLisa** [comment]
Thanks @gsvarma for the first implementation. Could you change two things?
- [ ] Please make the table resizable.
- [x] Allow the columns to be sortable (add a triangle next to the header of each column. On click, the table should sort itself by this column).

**Comment by ghost** [comment]
The first task will be considered in issue #30 and second task functionality is addressed by `table1->sort(true)`.  https://github.com/gapran/sim_platform/blob/f988cc792897f577e979c8a98bb62277799d2d6c/SimPlatform/Prototype1/main.cpp#L81
