### ISSUE TITLE
Text element

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/sim_platform#5]
Extend the default view.

- [x] Default text.

- Style
- [x] Colour
- [x] Background Colour
- [x] Bold
- [x] Size
- [x] Underline
- [x] Italic
- [x] Font family
------------

- [x] Link to the other views:
  * Table view: trigger a search on the searchable columns.

-----
-  Additional actions:

 ~Type~
- [x] Populate
- [x] Cancel
- [x]  Hover
- [x] Click

<img width="108" alt="capture d ecran 2019-02-11 a 13 25 25" src="https://user-images.githubusercontent.com/1546847/52563009-8b181600-2e00-11e9-91a0-5ad629771a4f.png">

**Comment by nguyenLisa** [comment]
Hi @gsvarma , you can start this by using @HaseebAhmad23 's code on the textelement branch.

**Comment by nguyenLisa** [comment]
Hi @gsvarma , could you replace the dummy text by a user-controlled text? (It should be set by the Prototype1 project.)

**Comment by ghost** [comment]
We do have a method which does that. Please help me understand if am missing something? @nguyenLisa 
```
void Text:: setText(QString text)
{

        textEdit->setText(text); //Setting Input Text
} 
```

**Comment by nguyenLisa** [comment]
Then, what is setPopulate() for?

**Comment by ghost** [comment]
`setPopulate()` populates the given text area, if in case a user wants to show a dummy text in the prototype.

https://github.com/gapran/sim_platform/blob/f988cc792897f577e979c8a98bb62277799d2d6c/SimPlatform/GpaLib/text.cpp#L115
