### ISSUE TITLE
Tab element

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/sim_platform#9]
Extends the default container.
- [x] List of tab names / tooltips
- [x] Additional actions:
  * Click on tab: load a sub-component.

<img width="654" alt="capture d ecran 2019-02-11 a 13 27 43" src="https://user-images.githubusercontent.com/1546847/52563140-da5e4680-2e00-11e9-9cce-4e7a38ee1522.png">

**Comment by osamic** [comment]
![tabs](https://user-images.githubusercontent.com/45318639/57841352-a5c8a500-77ca-11e9-8c77-707e872704a2.PNG)

**Comment by nguyenLisa** [comment]
b8d3da4
